motions:
  - file: ../data/step_left_002_Skeleton1.npz
    weight: 2.0
  - file: ../data/step_right_001_Skeleton1.npz
    weight: 2.0
  - file: ../data/walk_left_fast_001_Skeleton7.npz
    weight: 1.0
  - file: ../data/walk_left_slow_001_Skeleton7.npz
    weight: 1.0
  - file: ../data/walk_right_fast_001_Skeleton7.npz
    weight: 1.0
  - file: ../data/walk_right_slow_001_Skeleton7.npz
    weight: 1.0
  - file: ../data/walk_staight_fast_001_Skeleton7.npz
    weight: 1.0
  - file: ../data/walk_staight_slow_001_Skeleton7.npz
    weight: 1.0
    